// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zodiacEuropean.proto

package proto;

public final class ZodiacEuropean {
  private ZodiacEuropean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024zodiacEuropean.proto\032\ngate.proto2M\n\025Se" +
      "rviceZodiacEuropean\0224\n\021getZodiacEuropean" +
      "\022\016.PersonRequest\032\017.PersonResponseB\007\n\005pro" +
      "tob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.Gate.getDescriptor(),
        }, assigner);
    proto.Gate.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
